name: Fetch from issue
on: issue_comment
jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ (!github.event.issue.pull_request) && (github.event.issue.number == 5) }} 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "issue object #${{ github.event.issue.sender.organizations_url }}"
      
      

